### ISSUE TITLE
About categories

### ISSUE THREAD

**Issue by Holycomfort** [yangcaoai/CoDA_NeurIPS2023#1]
Hi,
Thanks for your great work! It seems the authors are busy and the code release may be later.  I wonder if you can share the names of base and novel categories on ScanNet and SUN-RGBD, that will make others easier to compare with CoDA. Thanks a lot!

**Comment by yangcaoai** [comment]
Hi, I have been dealing with several pressing deadlines recently. For the category names, please refer to the scripts and the codes within the data layers.

**Comment by yangcaoai** [comment]
Hi,  all the codes, data and pre-trained models have been at https://github.com/yangcaoai/CoDA_NeurIPS2023/tree/main
