### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by AmingWu** [yangcaoai/CoDA_NeurIPS2023#11]
Dear Authors,

When I train this code, there still exists an error:

![微信图片_20240620110059](https://github.com/yangcaoai/CoDA_NeurIPS2023/assets/38445175/e077d2be-ca96-4a8a-b33e-85bd60c8cd93)

**Comment by yangcaoai** [comment]
Hi, could you please check if there are available data under your data path (/data1/home/wyx/wam/CoDA/Data/sunrgbd_d/) and confirm if they are readable?

**Comment by yangcaoai** [comment]
Dear AmingWu, is your question solved? If it's fixed, I may close the issue. If not, feel free to contact me.
