### ISSUE TITLE
Dataset could not access

### ISSUE THREAD

**Issue by EinOnly** [yangcaoai/CoDA_NeurIPS2023#12]
https://hkustconnect-my.sharepoint.com/:f:/g/personal/ycaobd_connect_ust_hk/EqeHrtMq5aZBmnZUR79vub4B9HZIBxYLd5K7z6VuvemHzg?e=e7ooDv
can not open now.

**Comment by yangcaoai** [comment]
Hi, it's fixed. Please have a check.

**Comment by EinOnly** [comment]
Thanks! Btw, Does the program generate images like the image in the paper? I just made some hack to run it without your dataset, just get a *.lst file.

**Comment by yangcaoai** [comment]
It seems that you are evaluating the models by 'bash test_release_models.sh', so you will get the performance numbers in the *.lst files. If you want to predict samples, you can do so by running 'bash run_samples.sh'.
