### ISSUE TITLE
The train errors AttributeError: 'Model3DETRPredictedBoxDistillationHead' object has no attribute 'if_select_box_by_objectness'

### ISSUE THREAD

**Issue by 2490o** [yangcaoai/CoDA_NeurIPS2023#13]
I encountered the following problem when running bash scripts/coda_sunrgbd_stage1.sh
![image](https://github.com/yangcaoai/CoDA_NeurIPS2023/assets/118961872/ec056541-bd6b-48a7-9b23-aa1369b6b991)
When reviewing the code, I found that during initialization, the default setting is if_select_box_by_objectness=False. Do I need to modify the code?

**Comment by 2490o** [comment]
I modified the code by setting self.if_select_box_by_objectness = False and self.if_keep_box = False. This allows the code to run without errors. Is it okay to make these modifications, and will it affect the final results?
![image](https://github.com/yangcaoai/CoDA_NeurIPS2023/assets/118961872/ea1257ed-1a31-4a05-b13b-d2c487069c3c)

**Comment by yangcaoai** [comment]
Hi, they should be False. I have fixed the bug in https://github.com/yangcaoai/CoDA_NeurIPS2023/blob/main/models/model_3detr.py#L192
Please have a check

**Comment by 2490o** [comment]
Thank you very much, I'll give it a try.

**Comment by yangcaoai** [comment]
You're welcome. Feel free to ask if you have any questions. If you found the repo helpful, please consider giving it a star :)
