### ISSUE TITLE
The issues of "python: can't open file 'cloud_tools/mox.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by 2490o** [yangcaoai/CoDA_NeurIPS2023#14]
![image](https://github.com/yangcaoai/CoDA_NeurIPS2023/assets/118961872/7d56dedd-e20a-4504-9265-26ae75b53f53)
Could you please explain the purpose of the cloud_tools/mox.py file? Do I need to make any modifications to it?

**Comment by yangcaoai** [comment]
Hi, this script synchronizes my local and remote storage servers to help store files, and it has nothing to do with the methods. Therefore, you can ignore the warning. And I have fixed the warning. Thank you for the reminder.
