### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by JiangXiaobai00** [yangcaoai/CoDA_NeurIPS2023#15]
Hi, I encountered two issues during training: 1. The memory usage gradually increases during training, eventually resulting in an "out of memory" message; 2. There is a lack of data in the second phase of training: Data/sunrgb_d/sunrgbd_v1_revised_0415/sunrgbd_pc_bbox_votes_50k_v1_all_classes_revised_0415_noveltrain_pseudo_labels_setting0/007974_novel_bbox.npy.

**Comment by yangcaoai** [comment]
Hi (1) Which kind of GPU do you use and how much memory does it have? (2) Could you please check if the path ‘Data/sunrgb_d/sunrgbd_v1_revised_0415/sunrgbd_pc_bbox_votes_50k_v1_all_classes_revised_0415_noveltrain_pseudo_labels_setting0/’ exists?

**Comment by JiangXiaobai00** [comment]
Hello, regarding the first issue, I am using 8 I20-restricted GPUs with 48G each, and the memory usage has been gradually increasing from around 16G. I retrained, and now the memory usage has increased to 32G, and it seems like it will continue to grow. As for the second issue, the path indeed does not exist. May I ask if this is something that needs to be generated? If so, how can it be generated?

**Comment by yangcaoai** [comment]
Hi (1) The memory is more than enough for training.  I'm not sure why your training is increasing memory; my training and others haven't had this issue. You may need to debug the training process. 
(2) Yes, we need to store the discovered novel boxes in this path, so you'll need to create the empty path 'Data/sunrgb_d/sunrgbd_v1_revised_0415/sunrgbd_pc_bbox_votes_50k_v1_all_classes_revised_0415_noveltrain_pseudo_labels_setting0/’

**Comment by JiangXiaobai00** [comment]
Understood. For the first issue, based on the debugging results, it is suspected that some variables during the validation phase are not being released, as there is a significant increase in memory usage after validation. The training phase also sees an increase, but the magnitude is not as large.

**Comment by yangcaoai** [comment]
Interesting observation. Is the validation completely finished during training? (maybe you can check if the performance is successfully printed and if the performance number reasonable)

**Comment by JiangXiaobai00** [comment]
Thank you for your response. The performance is normal. And It seems that even without the testing phase, the memory is still not sufficient. I also experienced this with 4* 2080Ti GPUs for training; the memory usage increases by 10MB for every 10 training iterations.

**Comment by yangcaoai** [comment]
It's a bit strange. I've already used optimizer.zero_grad() during training, and model.eval() with @torch.no_grad() during testing to prevent gradients from accumulating. Besides, 8 I20-restricted GPUs with 48G each should be enough for training the model. The key is to solve the memory increasing issue.

**Comment by JiangXiaobai00** [comment]
Yes, it should be fine in theory, but the training always stops due to memory issues.

**Comment by yangcaoai** [comment]
Do you utilize 'PyTorch 1.8.1, torchvision==0.9.1, CUDA 10.1 and Python 3.7. '?

**Comment by JiangXiaobai00** [comment]
No, due to the CUDA version 11.7， i utilize the corresponding Python==3.8.19, PyTorch==2.0.1, torchvision==0.15.2.

**Comment by yangcaoai** [comment]
The reason may be the differences in the experiment environments.

**Comment by JiangXiaobai00** [comment]
Thanks. I will switch to the same environment to run the program and observe the memory situation.

**Comment by yangcaoai** [comment]
Yeah, my pleasure. If there are any questions, feel free to continue our discussion.

**Comment by JiangXiaobai00** [comment]
Thanks very much for your patient responses.

**Comment by JiangXiaobai00** [comment]
Hello, I've identified the module responsible for the escalating CUDA memory usage. Upon applying the detach() operation to the variables `gt_center_ori` and `objectness_prob` within the `_get_predicted_box_clip_embedding_` function of the `**Model3DETRPredictedBoxDistillationHead**` class in `model_3detr.py`, the memory consumption during training has stabilized:

```python
gt_center_ori = outputs["box_corners_xyz"].detach().clone()
objectness_prob = outputs["objectness_prob"].detach().clone()
```

From my perspective, theoretically, detaching these variables from the computation graph should not impact the network's training process, as they are intermediate steps in the calculation of the GT item for `_loss_predicted_region_embed_l1_`.

**Comment by yangcaoai** [comment]
> computation

Yes, they should not impact the training👍   I'm glad you solved the issue, which occurred in your experimental environment. We would appreciate it if you could submit a pull request to update the relevant parts, as this could assist other users with similar experimental environment

**Comment by yangcaoai** [comment]
> Hello, I've identified the module responsible for the escalating CUDA memory usage. Upon applying the detach() operation to the variables `gt_center_ori` and `objectness_prob` within the `_get_predicted_box_clip_embedding_` function of the `**Model3DETRPredictedBoxDistillationHead**` class in `model_3detr.py`, the memory consumption during training has stabilized:
> 
> ```python
> gt_center_ori = outputs["box_corners_xyz"].detach().clone()
> objectness_prob = outputs["objectness_prob"].detach().clone()
> ```
> 
> From my perspective, theoretically, detaching these variables from the computation graph should not impact the network's training process, as they are intermediate steps in the calculation of the GT item for `_loss_predicted_region_embed_l1_`.

Yes, they should not impact the training👍   I'm glad you solved the issue, which occurred in your experimental environment. We would appreciate it if you could submit a pull request to update the relevant parts, as this could assist other users with similar experimental environment
