### ISSUE TITLE
 Question on How the OV-dataset is Created

### ISSUE THREAD

**Issue by rasd3** [yangcaoai/CoDA_NeurIPS2023#16]
Could you confirm if the OV-SUN RGB-D and OV-ScanNet datasets provided via the link are updated from the existing base class datasets using the 3D-NOD strategy mentioned in the paper?

**Comment by yangcaoai** [comment]
Hi, the 3D-NOD strategy is designed to discover annotations for novel categories during training. The OV-SUN RGB-D and OV-ScanNet datasets are constructed using annotations from base categories in the original datasets. Therefore, the OV-SUN RGB-D and OV-ScanNet available through the link have not been updated yet. You'll need to update them through training.

**Comment by rasd3** [comment]
Thank you for the quick and kind response!
