### ISSUE TITLE
A problem during the second phase of training

### ISSUE THREAD

**Issue by NavyWork** [yangcaoai/CoDA_NeurIPS2023#17]
I have been reading your excellent paper and attempting to replicate your work. However, I encountered a problem during the second phase of training. Is it possible that the second phase is causing an infinite loop? According to the description in your paper, it seems that we only need to compare the results after 200 epochs. Does this mean that the experiment can be paused once 200 epochs have been completed?

I would greatly appreciate your clarification on this matter. Looking forward to your reply.

**Comment by yangcaoai** [comment]
Hi, thanks for your interest. The performance after 200 epochs is generally good enough, which is reported in our paper. However, you can continue training up to 400 or 600 epochs to select the best checkpoint in your environment.

**Comment by NavyWork** [comment]
Thank you for your detailed explanation. I understand your approach and appreciate the information provided.
