### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by AmingWu** [yangcaoai/CoDA_NeurIPS2023#7]
Dear Authors,

When I run this code, there exists an error:

FileNotFoundError: [Errno 2] No such file or directory: 'Data/sunrgb_d/sunrgbd_v1_revised_0415/sunrgbd_pc_bbox_votes_50k_v1_all_classes_revised_0415_minival'

**Comment by yangcaoai** [comment]
Hi, to fix the bug quickly, you can directly make an empty dir by:
`mkdir Data/sunrgb_d/sunrgbd_v1_revised_0415/sunrgbd_pc_bbox_votes_50k_v1_all_classes_revised_0415_minival`.

I utilize this dir for the evaluation on a mini-set for debugging, which has no influence on the normal training and testing.
