### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by AmingWu** [yangcaoai/CoDA_NeurIPS2023#8]
Dear Authors,

When I train this code, there is an error.

![捕获](https://github.com/yangcaoai/CoDA_NeurIPS2023/assets/38445175/4c93c0ee-72b6-4698-8dab-500e997c65e0)

**Comment by yangcaoai** [comment]
Hi, it seems that the data layer doesn't read an image successfully.

**Comment by AmingWu** [comment]
self.calib_path = "/data1/home/wyx/wam/CoDA/Data/sunrgb_d/"
self.image_path = "/data1/home/wyx/wam/CoDA/Data/sunrgb_d/", is this correct?

**Comment by yangcaoai** [comment]
Hi, please refer to the source code:
https://github.com/yangcaoai/CoDA_NeurIPS2023/blob/main/datasets/sunrgbd_anonymous_aligned_image_with_novel_cate_confi.py#L73
