### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by AmingWu** [yangcaoai/CoDA_NeurIPS2023#9]
Dear Authors,

I have downloaded your given data. But I do not run your code. There exist multiple errors：

![捕获](https://github.com/yangcaoai/CoDA_NeurIPS2023/assets/38445175/02958e55-1b1f-4710-95f0-99866a8d0688)

**Comment by yangcaoai** [comment]
Hi AmingWu, it seems there are some issues with your **data path**. You can check whether there really is data here, or whether the data here is readable.
